name: Pull request workflow2
        
on:
  pull_request:
    branches: [testtt]
    types: [closed]
jobs:
myjobtest1:
if: github.event.pull_request.merged == true
steps: // the rest of the code
  - name: step 1
  if: github.head_ref == 'dev'
  run: echo "gitara gra"
  